version: "2"

volumes:
  certs_data:
  portainer_data:

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs_data:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx:rw
    volumes:
      - certs_data:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=$DEFAULT_EMAIL
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - certs_data:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=$DNS_PORTAINER
      - LETSENCRYPT_HOST=$DNS_PORTAINER
      - LETSENCRYPT_EMAIL=$DEFAULT_EMAIL
