version: "2"

volumes:
  web_data:
  portainer_data:

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx:rw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=$DEFAULT_EMAIL
    network_mode: bridge
  portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - /portalavita/web:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=$DNS_PORTAINER
      - LETSENCRYPT_HOST=$DNS_PORTAINER
      - LETSENCRYPT_EMAIL=$DEFAULT_EMAIL
